base_model: NousResearch/Llama-2-7b-hf
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: true
load_in_4bit: false
strict: false

datasets:
  - path: newukdata_trim_nonan_2k.jsonl
    ds_type: json
    type: alpaca
  # - path: mhenrichsen/alpaca_2k_test
  #   type: alpaca
dataset_prepared_path:
val_set_size: 0.05
output_dir: ./lora-out

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

adapter: lora
lora_model_dir:
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:

# adapter: 
# lora_model_dir:
# lora_r: 
# lora_alpha: 
# lora_dropout: 
# lora_target_linear: 
# lora_fan_in_fan_out:

wandb_project: uk-finetuning
wandb_entity:
wandb_watch: gradients
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16: 
tf32: false

gradient_checkpointing: true
# early_stopping_patience: 2
resume_from_checkpoint:
# auto_resume_from_checkpoints: true
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
# flash_attn_cross_entropy: false
# flash_attn_rms_norm: true
# flash_attn_fuse_qkv: false
# flash_attn_fuse_mlp: true

warmup_steps: 10
#eval_steps: 0.05
evals_per_epoch: 4
eval_table_size:
eval_table_max_new_tokens: 128
save_steps: 0.10
debug: true
deepspeed: /root/axolotl/deepspeed_configs/zero2.json
#deepspeed: /root/axolotl/deepspeed_configs/zero3_bf16.json
weight_decay: 0.1
fsdp:
fsdp_config:
